### ISSUE TITLE
The plugin.json field "library" is deprecated

### ISSUE THREAD

**Issue by spin0us** [am1cable/nodebb-plugin-alignment#1]
I'm using your plugin on a fresh install of nodebb v1.18.6.

According to this warning message from the log :
```
warn:    [plugins/nodebb-plugin-alignment] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
```

Can you add this line to your package.json ?
```
"main": "library.js",
```

**Comment by 4m2c4bl3** [comment]
sorry, this plugin isn't maintained actively. i use an older version of nodebb so i have no need to update it until i eventually migrate to a newer nodebb
